spring.application.name=ngo-project

server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3306/ngo_platform
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=ngoSecretKey2025VeryLongSecureKey
app.jwt.expiration=86400000